import "./globals.css";
import { Inter } from "next/font/google";
import Layout from "../components/MainLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
    <html lang="pt-br">
      <body className={inter.className + " overflow-x-hidden"}>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  );
}
