import "./globals.css";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import { AuthProvider } from "@/contexts/authContext/AuthProvider";
import RouterProvider from "@/Router/RouterProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="pt-br">
      <body className={inter.className + " overflow-x-hidden"}>
        <AuthProvider>
          <RouterProvider>
            {children}
          </RouterProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
